server:
  port: 7003
eureka:
  instance:
    hostname: wanglihan03
  client:
    register-with-eureka: false #别把自己注册进去
    fetch-registry: false #自己是服务端
    service-url:
    # defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #声明 访问的路径是什么 单机版的 集群环境使用逗号进行分隔
      defaultZone: http://wanglihan01:7001/eureka/,http://wanglihan02:7002/eureka/
       