server:
  port: 8080

eureka:
  client:
    register-with-eureka: false # 消费者不用向服务端注册
    service-url:
      defaultZone: http://wanglihan01:7001/eureka/,http://wanglihan02:7002/eureka/,http://wanglihan03:7003/eureka/
