server:
 port: 8001
mybatis:
 config-location: classpath:mybatis/mybatiscfg.xml        # mybatis配置文件所在路径
 type-aliases-package: com.liuchuang.springcloud.entities    # 所有Entity别名类所在包
 mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
spring:
 application:
  name: microservicecloud-dept 
 datasource:
   type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
   driver-class-name: com.mysql.jdbc.Driver          # mysql驱动包
   url: jdbc:mysql://localhost:3306/cloudDB01              # 数据库名称
   username: root
   password: root
   dbcp2:
     min-idle: 5                                           # 数据库连接池的最小维持连接数
     initial-size: 5                                       # 初始化连接数
     max-total: 5                                          # 最大连接数
     max-wait-millis: 200                                  # 等待连接获取的最大超时时间
eureka:   
  instance:
   instance-id: microservicecloud-dept:8001 #修改默认访问服务名称 
   prefer-ip-address: true   #修改访问的链接 已IP的形式显示
  client:
    service-url:
      defaultZone: http://wanglihan01:7001/eureka/,http://wanglihan02:7002/eureka/,http://wanglihan03:7003/eureka/ #8001 注冊到 一下服務中     eureka 集群配置 使用逗号 ,进行区分间隔
info:
  app.name: atguigu-microservicecloud8001   #eureka 访问每一个微服务的 /info 的静态内容   build里面配置的 $
  company.name: www.atguigu.com         #eureka 访问每一个微服务的 /info 的静态内容 
  build.artifactId: microservicecloud-provider-dept-8001 #eureka 访问每一个微服务的 /info 的动态内容 
  build.version: 0.0.1-SNAPSHOT